michael = Artist.create(name: "Michael Jackson", age: rand(50), title: "King of Pop")
stevie = Artist.create(name: "Stevie Wonder", age: rand(50), title: "Little Stevie Wonder")
elvis = Artist.create(name: "Elvis Presley", age: rand(50), title: "the King")
whitney = Artist.create(name: "Whitney Houston", age: rand(50), title: "The Voice")
beyonce = Artist.create(name: "Beyoncé", age: rand(50), title: "Destiny's Child")

guitar = Instrument.create(name: "Guitar", classification: "Strings")
violin = Instrument.create(name: "Violin", classification: "Strings")
flute = Instrument.create(name: "Flute", classification: "Woodwind")
xylophone = Instrument.create(name: "Xylophone", classification: "Percussion")

ArtistInstrument.create(artist: michael, instrument: guitar)
ArtistInstrument.create(artist: stevie, instrument: guitar)
ArtistInstrument.create(artist: stevie, instrument: flute)
ArtistInstrument.create(artist: whitney, instrument: flute)
